### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by xyphro** [salakrzy/DTSU666_CHINT_to_HUAWEI_translator#5]
Hi!

After adding a meter to sun 2000 it sends:
0B 03 07 D1 00 01 D5 ED   which is answered by 0B 03 02 3F 80 30 15

Afterwards it sends:
0b 03 00 03 00 01 74 a0

So requests 1 register at address 0x0003. 

This address is not handed by this implementaiton.
I guess this popped up due to a FW update in the Sun2000 inverter.

Any idea?

Best regards,

Xyphro

**Comment by s-marian** [comment]
Hi, see my repository, it works perfectly for me, it is in production for 3 months already.

https://github.com/s-marian/DTSU666_CHINT_to_HUAWEI_translator

Marian

**Comment by Xyp** [comment]
The main difference seems to be that you return 0x3b11 as value for register read 0x7d1.

Will try this out, thanks Marian!

**Comment by s-marian** [comment]
Well, I can't remember the details but I had to do some address remapping and different scaling. Let me know if it works for you and tell me your inverter model too, thanks!

**Comment by Xyp** [comment]
Will try tomorrow. Inverter model is sun2000-10ktl-m1
Would love to find a full register readout for dtsu666-h, but don't know anybody that has one.

**Comment by s-marian** [comment]
Mine is also M1, so I am confident it will work well for you too.

I will send the dump from dtsu666-h in email.

**Comment by s-marian** [comment]
Pls write your email address here:)

**Comment by Xyp** [comment]
X_y_p_hro@gmail.com

Delete the underscores to get the real address.

**Comment by Xyp** [comment]
0x3b11 as response made the difference. Amazing! Would still be interested in a dump of all registers just to get a rough understanding what could go wrong in future sw updates

**Comment by s-marian** [comment]
Hi, I sent an email with the dump, didn't you receive it?
Glad that it works!

**Comment by Xyp** [comment]
No, did not receive. Will adjust this thing for sdm630 meter! Thanks for your help!

**Comment by gytisgreitai** [comment]
Hey, would it be possible to get the dump published somewhere? Thanks!

**Comment by radplo** [comment]
@s-marian and @salakrzy can you help me with freeRTOS "main_task" and "app_main" issue? I want to connect DTSU666 Basic version with SUN2000-5KTL-M1...

**Comment by salakrzy** [comment]
This issue is fixed in a newer version.

**Comment by xyphro** [comment]
Have also fixed it here: https://github.com/xyphro/Sun2000MeterTransposer
